runtime: nodejs20  # Or another suitable Node.js version

handlers:
- url: /
  static_files: dist/vulnerability-database-frontend/browser/index.html
  upload: dist/vulnerability-database-frontend/browser/index.html
- url: /
  static_dir: dist/vulnerability-database-frontend/browser


